services:
  tg_comments_archive:
    build: .
    image: tg_comments_archive
    container_name: tg_comments_archive
    network_mode: "host"
    tty: true
    stdin_open: true
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./account.session:/app/account.session